### ISSUE TITLE
403 Forbidden - Daily snapshots can't be downloaded since yesterday

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/website#164]
Daily snapshots can't be downloaded since yesterday:

```
403 Forbidden

    Code: SignatureDoesNotMatch
    RequestId: 
    HostId: 2730a77-prg-eu-1
```

Go to https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-all-languages.zip
